version: '2'

# Purpose is to test compatibility in Python 2.7 and Python 3.4
# TODO: add tests
# Brings up two machines, one with python 3.4 one with python 2.7
# Database by SQLITE
# Config settings copied from install

services:
  bots27:
    build:
      context: .
      dockerfile: ./compose/bots_py27/Dockerfile
    volumes:
      - ./mounts/usersys:/usr/local/lib/python2.7/site-packages/bots/usersys
      - ./mounts/botssys:/usr/local/lib/python2.7/site-packages/bots/botssys
      - ./mounts/config:/usr/local/lib/python2.7/site-packages/bots/config
    ports:
      - "0.0.0.0:8081:8080"

